import { Controller, Get, Post, Body, Param } from '@nestjs/common';
import { AgentAnalyticsReporterService } from '../services/agent-analytics-reporter.service';
import { CreateAgentAnalyticsReporterDto } from '../dto/create-agent-analytics-reporter.dto';
// Swagger imports
import {
  ApiTags,
  ApiOperation,
  ApiResponse,
  ApiBody,
  ApiParam,
} from '@nestjs/swagger';

@ApiTags('analytics-reporter')
@Controller('agents/analytics-reporter')
export class AgentAnalyticsReporterController {
  constructor(private readonly service: AgentAnalyticsReporterService) {}

  @Post()
  @ApiOperation({
    summary: 'Generate analytics reports',
    description:
      'Create comprehensive analytics reports based on specified metrics and time periods',
  })
  @ApiBody({
    description: 'Analytics report generation parameters',
    schema: {
      type: 'object',
      properties: {
        sessionId: { type: 'string', example: 'user-session-123' },
        reportType: {
          type: 'string',
          example: 'performance',
          description:
            'Type of report (performance, audience, comparison, custom)',
        },
        timePeriod: {
          type: 'string',
          example: 'last_30_days',
          description:
            'Time period for analysis (last_7_days, last_30_days, custom)',
        },
        metrics: {
          type: 'array',
          items: { type: 'string' },
          example: ['engagement_rate', 'reach', 'impressions'],
          description: 'Specific metrics to include in the report',
        },
        format: {
          type: 'string',
          example: 'pdf',
          description: 'Output format (pdf, csv, json, dashboard)',
        },
        platform: {
          type: 'string',
          example: 'all',
          description:
            'Social media platform (all, instagram, facebook, twitter, etc.)',
        },
      },
      required: ['sessionId', 'reportType', 'timePeriod'],
    },
  })
  @ApiResponse({
    status: 201,
    description: 'Analytics report generated successfully',
    schema: {
      type: 'object',
      properties: {
        id: { type: 'string', example: 'uuid-123' },
        sessionId: { type: 'string', example: 'user-session-123' },
        status: { type: 'string', example: 'completed' },
        result: {
          type: 'object',
          properties: {
            reportUrl: {
              type: 'string',
              example: 'https://reports.example.com/report.pdf',
            },
            metrics: {
              type: 'object',
              properties: {
                engagementRate: { type: 'number', example: 4.2 },
                reach: { type: 'number', example: 15000 },
                impressions: { type: 'number', example: 65000 },
              },
            },
            insights: { type: 'array', items: { type: 'string' } },
            recommendations: { type: 'array', items: { type: 'string' } },
          },
        },
        createdAt: { type: 'string', format: 'date-time' },
      },
    },
  })
  @ApiResponse({ status: 400, description: 'Invalid parameters provided' })
  async create(@Body() dto: CreateAgentAnalyticsReporterDto) {
    return this.service.create(dto);
  }

  @Get()
  @ApiOperation({
    summary: 'Get all analytics reports',
    description:
      'Retrieve a list of all analytics reports generated by this agent',
  })
  @ApiResponse({
    status: 200,
    description: 'List of analytics reports',
    schema: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          id: { type: 'string' },
          sessionId: { type: 'string' },
          status: { type: 'string' },
          result: { type: 'object' },
          createdAt: { type: 'string', format: 'date-time' },
        },
      },
    },
  })
  async findAll() {
    return this.service.findAll();
  }

  @Get(':id')
  @ApiOperation({
    summary: 'Get analytics report by ID',
    description: 'Retrieve details of a specific analytics report by its ID',
  })
  @ApiParam({
    name: 'id',
    description: 'Analytics report ID',
    example: '123e4567-e89b-12d3-a456-426614174000',
  })
  @ApiResponse({
    status: 200,
    description: 'Analytics report details',
    schema: {
      type: 'object',
      properties: {
        id: { type: 'string' },
        sessionId: { type: 'string' },
        status: { type: 'string' },
        result: { type: 'object' },
        createdAt: { type: 'string', format: 'date-time' },
      },
    },
  })
  @ApiResponse({ status: 404, description: 'Analytics report not found' })
  async findOne(@Param('id') id: string) {
    return this.service.findOne(id);
  }
}
