"use strict";
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
var __metadata = (this && this.__metadata) || function (k, v) {
    if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(k, v);
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.ProcessResponseDto = exports.MetricsDto = exports.RoutingDecisionDto = exports.ActionDto = void 0;
const swagger_1 = require("@nestjs/swagger");
class ActionDto {
}
exports.ActionDto = ActionDto;
__decorate([
    (0, swagger_1.ApiProperty)({
        description: 'Type of action to be executed',
        example: 'create_order'
    }),
    __metadata("design:type", String)
], ActionDto.prototype, "type", void 0);
__decorate([
    (0, swagger_1.ApiProperty)({
        description: 'Parameters for the action',
        example: { productId: 'prod-123', quantity: 2 }
    }),
    __metadata("design:type", Object)
], ActionDto.prototype, "params", void 0);
__decorate([
    (0, swagger_1.ApiPropertyOptional)({
        description: 'Status of the action',
        example: 'pending'
    }),
    __metadata("design:type", String)
], ActionDto.prototype, "status", void 0);
__decorate([
    (0, swagger_1.ApiPropertyOptional)({
        description: 'Target agent or service for this action',
        example: 'orders-service'
    }),
    __metadata("design:type", String)
], ActionDto.prototype, "target", void 0);
class RoutingDecisionDto {
}
exports.RoutingDecisionDto = RoutingDecisionDto;
__decorate([
    (0, swagger_1.ApiProperty)({
        description: 'Primary agent to handle the request',
        example: 'orders-agent'
    }),
    __metadata("design:type", String)
], RoutingDecisionDto.prototype, "primaryAgent", void 0);
__decorate([
    (0, swagger_1.ApiPropertyOptional)({
        description: 'Fallback agents if primary fails',
        example: ['support-agent', 'front-desk-agent']
    }),
    __metadata("design:type", Array)
], RoutingDecisionDto.prototype, "fallbackAgents", void 0);
__decorate([
    (0, swagger_1.ApiProperty)({
        description: 'Confidence score of routing decision (0-1)',
        example: 0.92
    }),
    __metadata("design:type", Number)
], RoutingDecisionDto.prototype, "confidence", void 0);
__decorate([
    (0, swagger_1.ApiPropertyOptional)({
        description: 'Reasoning for the routing decision'
    }),
    __metadata("design:type", String)
], RoutingDecisionDto.prototype, "reasoning", void 0);
class MetricsDto {
}
exports.MetricsDto = MetricsDto;
__decorate([
    (0, swagger_1.ApiProperty)({
        description: 'Total processing time in milliseconds',
        example: 1250
    }),
    __metadata("design:type", Number)
], MetricsDto.prototype, "processingTimeMs", void 0);
__decorate([
    (0, swagger_1.ApiProperty)({
        description: 'Number of LLM tokens consumed',
        example: 450
    }),
    __metadata("design:type", Number)
], MetricsDto.prototype, "tokensConsumed", void 0);
__decorate([
    (0, swagger_1.ApiProperty)({
        description: 'Number of vector embeddings retrieved',
        example: 5
    }),
    __metadata("design:type", Number)
], MetricsDto.prototype, "embeddingsUsed", void 0);
__decorate([
    (0, swagger_1.ApiProperty)({
        description: 'Cache hit/miss status',
        example: 'hit'
    }),
    __metadata("design:type", String)
], MetricsDto.prototype, "cacheStatus", void 0);
__decorate([
    (0, swagger_1.ApiPropertyOptional)({
        description: 'Additional performance metrics'
    }),
    __metadata("design:type", Object)
], MetricsDto.prototype, "additional", void 0);
class ProcessResponseDto {
}
exports.ProcessResponseDto = ProcessResponseDto;
__decorate([
    (0, swagger_1.ApiProperty)({
        description: 'Correlation ID for tracing',
        example: '550e8400-e29b-41d4-a716-446655440000'
    }),
    __metadata("design:type", String)
], ProcessResponseDto.prototype, "correlationId", void 0);
__decorate([
    (0, swagger_1.ApiProperty)({
        description: 'Session ID',
        example: 'session-uuid-456'
    }),
    __metadata("design:type", String)
], ProcessResponseDto.prototype, "sessionId", void 0);
__decorate([
    (0, swagger_1.ApiProperty)({
        description: 'Response text generated by the agent',
        example: 'I found the Nike Kobe shoes in your cart. Would you like to proceed with checkout?'
    }),
    __metadata("design:type", String)
], ProcessResponseDto.prototype, "responseText", void 0);
__decorate([
    (0, swagger_1.ApiPropertyOptional)({
        type: [ActionDto],
        description: 'Actions to be executed by downstream agents'
    }),
    __metadata("design:type", Array)
], ProcessResponseDto.prototype, "actions", void 0);
__decorate([
    (0, swagger_1.ApiPropertyOptional)({
        type: RoutingDecisionDto,
        description: 'Routing decision made by meta-agent'
    }),
    __metadata("design:type", RoutingDecisionDto)
], ProcessResponseDto.prototype, "routingDecision", void 0);
__decorate([
    (0, swagger_1.ApiProperty)({
        type: MetricsDto,
        description: 'Performance metrics for this request'
    }),
    __metadata("design:type", MetricsDto)
], ProcessResponseDto.prototype, "metrics", void 0);
__decorate([
    (0, swagger_1.ApiProperty)({
        description: 'Timestamp of response',
        example: '2025-12-04T10:30:00.000Z'
    }),
    __metadata("design:type", String)
], ProcessResponseDto.prototype, "timestamp", void 0);
__decorate([
    (0, swagger_1.ApiPropertyOptional)({
        description: 'Additional metadata'
    }),
    __metadata("design:type", Object)
], ProcessResponseDto.prototype, "metadata", void 0);
//# sourceMappingURL=process-response.dto.js.map