import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

export class ActionDto {
  @ApiProperty({
    description: 'Type of action to be executed',
    example: 'create_order'
  })
  type: string;

  @ApiProperty({
    description: 'Parameters for the action',
    example: { productId: 'prod-123', quantity: 2 }
  })
  params: Record<string, any>;

  @ApiPropertyOptional({
    description: 'Status of the action',
    example: 'pending'
  })
  status?: 'pending' | 'sent' | 'processing' | 'completed' | 'failed';

  @ApiPropertyOptional({
    description: 'Target agent or service for this action',
    example: 'orders-service'
  })
  target?: string;
}

export class RoutingDecisionDto {
  @ApiProperty({
    description: 'Primary agent to handle the request',
    example: 'orders-agent'
  })
  primaryAgent: string;

  @ApiPropertyOptional({
    description: 'Fallback agents if primary fails',
    example: ['support-agent', 'front-desk-agent']
  })
  fallbackAgents?: string[];

  @ApiProperty({
    description: 'Confidence score of routing decision (0-1)',
    example: 0.92
  })
  confidence: number;

  @ApiPropertyOptional({
    description: 'Reasoning for the routing decision'
  })
  reasoning?: string;
}

export class MetricsDto {
  @ApiProperty({
    description: 'Total processing time in milliseconds',
    example: 1250
  })
  processingTimeMs: number;

  @ApiProperty({
    description: 'Number of LLM tokens consumed',
    example: 450
  })
  tokensConsumed: number;

  @ApiProperty({
    description: 'Number of vector embeddings retrieved',
    example: 5
  })
  embeddingsUsed: number;

  @ApiProperty({
    description: 'Cache hit/miss status',
    example: 'hit'
  })
  cacheStatus: 'hit' | 'miss' | 'partial';

  @ApiPropertyOptional({
    description: 'Additional performance metrics'
  })
  additional?: Record<string, any>;
}

export class ProcessResponseDto {
  @ApiProperty({
    description: 'Correlation ID for tracing',
    example: '550e8400-e29b-41d4-a716-446655440000'
  })
  correlationId: string;

  @ApiProperty({
    description: 'Session ID',
    example: 'session-uuid-456'
  })
  sessionId: string;

  @ApiProperty({
    description: 'Response text generated by the agent',
    example: 'I found the Nike Kobe shoes in your cart. Would you like to proceed with checkout?'
  })
  responseText: string;

  @ApiPropertyOptional({
    type: [ActionDto],
    description: 'Actions to be executed by downstream agents'
  })
  actions?: ActionDto[];

  @ApiPropertyOptional({
    type: RoutingDecisionDto,
    description: 'Routing decision made by meta-agent'
  })
  routingDecision?: RoutingDecisionDto;

  @ApiProperty({
    type: MetricsDto,
    description: 'Performance metrics for this request'
  })
  metrics: MetricsDto;

  @ApiProperty({
    description: 'Timestamp of response',
    example: '2025-12-04T10:30:00.000Z'
  })
  timestamp: string;

  @ApiPropertyOptional({
    description: 'Additional metadata'
  })
  metadata?: Record<string, any>;
}
