import { Controller, Get, Post, Body, Param } from '@nestjs/common';
import { AgentFaqResponderService } from '../services/agent-faq-responder.service';
import { CreateAgentFaqResponderDto } from '../dto/create-agent-faq-responder.dto';
// Swagger imports
import {
  ApiTags,
  ApiOperation,
  ApiResponse,
  ApiBody,
  ApiParam,
} from '@nestjs/swagger';

@ApiTags('faq-responder')
@Controller('agents/faq-responder')
export class AgentFaqResponderController {
  constructor(private readonly service: AgentFaqResponderService) {}

  @Post()
  @ApiOperation({
    summary: 'Generate FAQ responses',
    description:
      'Create comprehensive FAQ responses based on provided topics or questions',
  })
  @ApiBody({
    description: 'FAQ generation parameters',
    schema: {
      type: 'object',
      properties: {
        sessionId: { type: 'string', example: 'user-session-123' },
        topic: {
          type: 'string',
          example: 'product returns and refunds',
          description: 'Topic or category for FAQ generation',
        },
        question: {
          type: 'string',
          example: 'How do I return a product?',
          description:
            'Specific question to answer (optional if topic is provided)',
        },
        audience: {
          type: 'string',
          example: 'customers',
          description: 'Target audience for the FAQ responses',
        },
        detailLevel: {
          type: 'string',
          example: 'comprehensive',
          description: 'Level of detail (basic, standard, comprehensive)',
        },
        format: {
          type: 'string',
          example: 'list',
          description: 'Response format (list, article, dialogue)',
        },
      },
      required: ['sessionId', 'topic'],
    },
  })
  @ApiResponse({
    status: 201,
    description: 'FAQ responses generated successfully',
    schema: {
      type: 'object',
      properties: {
        id: { type: 'string', example: 'uuid-123' },
        sessionId: { type: 'string', example: 'user-session-123' },
        status: { type: 'string', example: 'completed' },
        result: {
          type: 'object',
          properties: {
            questions: {
              type: 'array',
              items: {
                type: 'object',
                properties: {
                  question: { type: 'string' },
                  answer: { type: 'string' },
                  category: { type: 'string' },
                  confidence: { type: 'number' },
                },
              },
            },
            summary: { type: 'string' },
          },
        },
        createdAt: { type: 'string', format: 'date-time' },
      },
    },
  })
  @ApiResponse({ status: 400, description: 'Invalid parameters provided' })
  async create(@Body() dto: CreateAgentFaqResponderDto) {
    return this.service.create(dto);
  }

  @Get()
  @ApiOperation({
    summary: 'Get all FAQ responses',
    description: 'Retrieve a list of all FAQ responses generated by this agent',
  })
  @ApiResponse({
    status: 200,
    description: 'List of FAQ responses',
    schema: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          id: { type: 'string' },
          sessionId: { type: 'string' },
          status: { type: 'string' },
          result: { type: 'object' },
          createdAt: { type: 'string', format: 'date-time' },
        },
      },
    },
  })
  async findAll() {
    return this.service.findAll();
  }

  @Get(':id')
  @ApiOperation({
    summary: 'Get FAQ response by ID',
    description: 'Retrieve details of a specific FAQ response by its ID',
  })
  @ApiParam({
    name: 'id',
    description: 'FAQ response ID',
    example: '123e4567-e89b-12d3-a456-426614174000',
  })
  @ApiResponse({
    status: 200,
    description: 'FAQ response details',
    schema: {
      type: 'object',
      properties: {
        id: { type: 'string' },
        sessionId: { type: 'string' },
        status: { type: 'string' },
        result: { type: 'object' },
        createdAt: { type: 'string', format: 'date-time' },
      },
    },
  })
  @ApiResponse({ status: 404, description: 'FAQ response not found' })
  async findOne(@Param('id') id: string) {
    return this.service.findOne(id);
  }
}
