import { Controller, Get, Post, Body, Param } from '@nestjs/common';
import { AgentFaqResponderV2Service } from '../services/agent-faq-responder-v2.service';
import { CreateAgentFaqResponderDto } from '../dto/create-agent-faq-responder.dto';
// Swagger imports
import {
  ApiTags,
  ApiOperation,
  ApiResponse,
  ApiBody,
  ApiParam,
} from '@nestjs/swagger';

@ApiTags('agents')
@Controller('v2/agents/faq-responder')
export class AgentFaqResponderV2Controller {
  constructor(private readonly service: AgentFaqResponderV2Service) {}

  @Post()
  @ApiOperation({
    summary: 'Generate FAQ responses (V2)',
    description:
      'Generate comprehensive FAQ responses based on topics with enhanced capabilities',
  })
  @ApiBody({
    description: 'FAQ generation parameters',
    schema: {
      type: 'object',
      properties: {
        sessionId: { type: 'string', example: 'user-session-123' },
        topic: {
          type: 'string',
          example: 'product returns and refunds',
          description: 'Topic for FAQ generation',
        },
        audience: {
          type: 'string',
          example: 'customers',
          description: 'Target audience for FAQ responses',
        },
        detailLevel: {
          type: 'string',
          example: 'comprehensive',
          description: 'Level of detail (basic, standard, comprehensive)',
        },
        format: {
          type: 'string',
          example: 'list',
          description: 'Response format (list, categorized, structured)',
        },
      },
      required: ['sessionId', 'topic', 'audience'],
    },
  })
  @ApiResponse({
    status: 201,
    description: 'FAQ responses generated successfully',
    schema: {
      type: 'object',
      properties: {
        success: { type: 'boolean', example: true },
        data: {
          type: 'object',
          properties: {
            faq: {
              type: 'object',
              properties: {
                id: { type: 'string' },
                sessionId: { type: 'string' },
                status: { type: 'string' },
                createdAt: { type: 'string', format: 'date-time' },
              },
            },
            questions: {
              type: 'array',
              items: {
                type: 'object',
                properties: {
                  question: { type: 'string' },
                  answer: { type: 'string' },
                  confidence: { type: 'number' },
                  category: { type: 'string' },
                },
              },
            },
            topic: { type: 'string' },
            audience: { type: 'string' },
            format: { type: 'string' },
          },
        },
        metrics: {
          type: 'object',
          properties: {
            requestsProcessed: { type: 'number' },
            successRate: { type: 'number' },
            avgResponseTime: { type: 'number' },
            errors: { type: 'number' },
            lastActive: { type: 'string', format: 'date-time' },
          },
        },
      },
    },
  })
  @ApiResponse({ status: 400, description: 'Invalid parameters provided' })
  async create(@Body() dto: CreateAgentFaqResponderDto) {
    return this.service.execute(dto);
  }

  @Get()
  @ApiOperation({
    summary: 'Get all FAQ responses (V2)',
    description:
      'Retrieve a list of all FAQ responses generated by this agent',
  })
  @ApiResponse({
    status: 200,
    description: 'List of FAQ responses',
    schema: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          id: { type: 'string' },
          sessionId: { type: 'string' },
          status: { type: 'string' },
          createdAt: { type: 'string', format: 'date-time' },
        },
      },
    },
  })
  async findAll() {
    return this.service.findAll();
  }

  @Get(':id')
  @ApiOperation({
    summary: 'Get FAQ response by ID (V2)',
    description: 'Retrieve details of a specific FAQ response by its ID',
  })
  @ApiParam({
    name: 'id',
    description: 'FAQ response ID',
    example: '123e4567-e89b-12d3-a456-426614174000',
  })
  @ApiResponse({
    status: 200,
    description: 'FAQ response details',
    schema: {
      type: 'object',
      properties: {
        id: { type: 'string' },
        sessionId: { type: 'string' },
        status: { type: 'string' },
        createdAt: { type: 'string', format: 'date-time' },
      },
    },
  })
  @ApiResponse({ status: 404, description: 'FAQ response not found' })
  async findOne(@Param('id') id: string) {
    return this.service.findOne(id);
  }

  @Get('session/:sessionId')
  @ApiOperation({
    summary: 'Get FAQ responses by session (V2)',
    description: 'Retrieve all FAQ responses created during a specific session',
  })
  @ApiParam({
    name: 'sessionId',
    description: 'Session ID',
    example: 'user-session-123',
  })
  @ApiResponse({
    status: 200,
    description: 'FAQ responses for session',
    schema: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          id: { type: 'string' },
          sessionId: { type: 'string' },
          status: { type: 'string' },
          createdAt: { type: 'string', format: 'date-time' },
        },
      },
    },
  })
  async findBySession(@Param('sessionId') sessionId: string) {
    return this.service.findBySessionId(sessionId);
  }

  @Get('metrics')
  @ApiOperation({
    summary: 'Get agent metrics (V2)',
    description: 'Retrieve performance metrics for this agent',
  })
  @ApiResponse({
    status: 200,
    description: 'Agent metrics',
    schema: {
      type: 'object',
      properties: {
        totalFaqs: { type: 'number' },
        dbSuccessRate: { type: 'number' },
        dbFailureRate: { type: 'number' },
        requestsProcessed: { type: 'number' },
        avgResponseTime: { type: 'number' },
        errors: { type: 'number' },
        lastActive: { type: 'string', format: 'date-time' },
      },
    },
  })
  async getMetrics() {
    return this.service.getMetrics();
  }
}